### PR TITLE
add org_id to people.getBy function

### PR DESCRIPTION
**Pull request by jay-meister**
we forgot to add org_id to getBy function.

### CODE REVIEW

**Comment by jay-meister** [comment]
do i need to update package json?

**Review by mk4111 — APPROVED** [review]
LGTM!

**Comment by mk4111** [comment]
I think a minor upgrade would be good - it will be a necessary part of our app!

**Comment by jay-meister** [comment]
ok done @SimonLab

**Comment by jay-meister** [comment]
closing as i mistakenly pushed different commits up to this branch

**Pull request closed without merging**
