### PR TITLE
add org query and function

### PR DESCRIPTION
**Pull request by jay-meister**
add organisation query and function with tests

payload may or may not include the logo_url and mission_statement so we enter nulls if they are not included.

relates to:
https://github.com/emfoundation/ce100-app/issues/415

### CODE REVIEW

**Review by mk4111 — APPROVED** [review]
LGTM! :taco:

**Comment by jay-meister** [comment]
Thanks @mk4111

**Comment by mk4111** [comment]
@JMurphyWeb no more mission statement? How comes?

**Comment by jay-meister** [comment]
https://app.zeplin.io/project.html#pid=57ac9b5692d0c316520caeca&sid=582b5273d7d77de65b946ab2

**Review by SimonLab — APPROVED** [review]
Looks good @JMurphyWeb , thanks @mk4111 for the review

**Pull request merged**
